### PR TITLE
ENH: make cache clearing optional

### LINKED ISSUE #236: Clearing cuda cache during interpolation is slow
Hi @EmmaRenauld !

I was profiling my training and noticed that "torch._C._cuda_emptyCache()" was slowing down my tracking process quite a lot.

image

Looking at `dwi_ml.data.processing.volume.interpolation.interpolate_volume_in_neighborhood` (https://github.com/scil-vital/dwi_ml/blob/master/dwi_ml/data/processing/volume/interpolation.py#L166), the comment does mention that it may be a bit low but saves on memory. Would it be possible to make clearing the cache optional ? Or leave it to the user ? Personally I never encountered memory leaks due to this.

Thanks !

### PR DESCRIPTION
**Pull request by AntoineTheb**
## Description
Fix #236 

## Have you
- [X] Added a description of the content of this PR above
- [X] Followed [proper commit message formatting](https://chris.beams.io/posts/git-commit/)
- [ ] Added data and a script to test this PR
- [ ] Made sure that PEP8 issues are resolved
- [ ] Tested the code yourself right before pushing
- [ ] Added unit tests to test the code you implemented

## People this PR concerns
@EmmaRenauld

### CODE REVIEW

**Review by EmmaRenauld — APPROVED** [review]
Ok for me. However, if you want this to be really complete, it would need to be an option of the batch_loader, which takes care of the interpolation. But if it answers your needs for now, ok for me.

**Comment by AntoineTheb** [comment]
From what I found the files that import `interpolation` are
`dwi_ml/models/main_models.py`
`dwi_ml/tracking/tracking_mask.py`

I added the option in `tracking_mask`, but not in `main_models` as the object structure is a bit complex and dependant to your use case. If you can point me to where the option should be added I can include it, otherwise I think this could work as is. Thanks !

**Comment by EmmaRenauld** [comment]
> From what I found the files that import `interpolation` are `dwi_ml/models/main_models.py` `dwi_ml/tracking/tracking_mask.py`
> 
> I added the option in `tracking_mask`, but not in `main_models` as the object structure is a bit complex and dependant to your use case. If you can point me to where the option should be added I can include it, otherwise I think this could work as is. Thanks !

Yeah... It's a bit convoluted, and the doc is not up-to-date, sorry. In the case where you need one input in your model, from one group in the hdf5, you can use the classes `DWIMLTrainerOneInput`, `DWIMLBatchLoaderOneInput`, and `MainModelOneInput`. Here's how they interact:


- The trainer gets the inputs from the batch loader at line 1128 in `dwi_ml.training.trainers`:
`batch_inputs = self.batch_loader.load_batch_inputs(streamlines_f, ids_per_subj)`

- The batch_loader is the class that knows to access the hdf5 for each subjects. But it formats the inputs based on how the model tells it to at line 405 in `dwi_ml.training.batch_loaders`:
`subbatch_x_data = self.model.prepare_batch_one_input(streamlines, self.context_subset, subj, self.input_group_idx)`

- This calls the model's method, either at line 452 in `dwi_ml.models.main_models`, or maybe you can overwrite it in your own model based on your needs.


So.. I think I would add it as a parameter of the batch_loader: in the `__init__` at line 328, and then when you call the method at line 405. Just set it to true by default, I'll see eventually if I want to add the option in the learn2track script and transformer script.

**Comment by AntoineTheb** [comment]
Sorry for the late update @EmmaRenauld, let me know if that corresponds to what you wanted.

**Review by EmmaRenauld — APPROVED** [review]

**Pull request merged**
